### ISSUE TITLE
CMake cannot locate boost which is installed in /usr/include/boost

### ISSUE THREAD

**Issue by dispersed** [kingsfordgroup/sailfish#14] opened 2014-04-23 16:16 UTC
I tried to build sailfish from source on Debian. Problem is, Boost is not found. I wouldn't like to edit the CMakeLists.txt and wouldn't know directly what to do either. Boost is installed in /usr/include/boost which seems like a standard location. I have tested with versions 1.49, 1.53 and 1.55, but the problem doesn't seem to depend on the version of boost. I also tried to specify the -DFETCH_BOOST=TRUE option but unfortunately, boost failed to build. To be honest, I wouldn't like to build it either. Thanks.

**Comment by rob-p** [comment] 2015-10-16 21:27
Boost is one of the biggest culprits in terms of build troubles.  However, as I've recently been unable to reproduce any such build errors with the newer releases, I'm closing this issue for now.  Please let me know if you continue to have any of these issues.  One very strange quirk of CMake that I've noticed is that if you specify a custom Boost path (e.g. `BOOST_ROOT`), you must specify the **fully-qualified** path — relative paths are not handled properly by the build system.

**Closed by rob-p** 2015-10-16 21:27 UTC
